### PR TITLE
PSG-4533: Added namespace in build.gradle

### PR DESCRIPTION
**Pull request by SinaSeylani**

### CODE REVIEW

**Comment by plchekspend** [comment]
@SinaSeylani thanks for this changes 
but according to flutter sdk 3.19.0 you have to migrate the android gradle files,
you can have look for this official [documentation](https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply)

**Review by flanagankp — APPROVED** [review]

**Comment by plchekspend** [comment]
@flanagankp  please look for above documentation as those are necessary migration to support latest flutter SDK versions.
Thanks

**Review by flanagankp — CHANGES_REQUESTED** [review]
See above comment about current flutter SDKs

**Comment by SinaSeylani** [comment]
@flanagankp @plchekspend ,The recommended changes for Flutter SDK 3.19.0 and later have been added.

**Review by flanagankp — APPROVED** [review]

**Pull request merged**
